# Generated by Django 3.1.4 on 2022-07-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование сырья')),
                ('component_Fe', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Fe')),
                ('component_Si', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Si')),
                ('component_Al', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Al')),
                ('component_Ca', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Ca')),
                ('component_S', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='S')),
                ('report_year', models.DecimalField(decimal_places=0, default=2022, max_digits=4, verbose_name='Год')),
                ('report_month', models.DecimalField(decimal_places=0, default=1, max_digits=2, verbose_name='Месяц')),
                ('report_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('report_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('author_name', models.CharField(default='', max_length=255, verbose_name='Автор')),
            ],
        ),
    ]
