# Generated by Django 3.1.4 on 2022-08-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='component_Al',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Al'),
        ),
        migrations.AlterField(
            model_name='report',
            name='component_Ca',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Ca'),
        ),
        migrations.AlterField(
            model_name='report',
            name='component_Fe',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Fe'),
        ),
        migrations.AlterField(
            model_name='report',
            name='component_S',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='S'),
        ),
        migrations.AlterField(
            model_name='report',
            name='component_Si',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Si'),
        ),
    ]
