# Generated by Django 3.1.4 on 2022-08-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20220802_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='author_name',
            field=models.CharField(default='', max_length=255, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='report',
            name='component_Al',
            field=models.FloatField(verbose_name='Al'),
        ),
        migrations.AlterField(
            model_name='report',
            name='component_Ca',
            field=models.FloatField(verbose_name='Ca'),
        ),
        migrations.AlterField(
            model_name='report',
            name='component_Fe',
            field=models.FloatField(verbose_name='Fe'),
        ),
        migrations.AlterField(
            model_name='report',
            name='component_S',
            field=models.FloatField(verbose_name='S'),
        ),
        migrations.AlterField(
            model_name='report',
            name='component_Si',
            field=models.FloatField(verbose_name='Si'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time create'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_month',
            field=models.FloatField(default=1, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Time update'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_year',
            field=models.FloatField(default=2022, verbose_name='Year'),
        ),
    ]
