# Generated by Django 3.1.4 on 2022-08-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20220802_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_year',
            field=models.DecimalField(decimal_places=0, default=2022, max_digits=4, verbose_name='Year'),
        ),
    ]
